class Organisation { constructor({icon,bg,name,desc,url,tag,cls}){this.icon=icon;this.bg=bg;this.name=name;this.desc=desc;this.url=url;this.tag=tag;this.cls=cls;} }
const organisations=[
    new Organisation({icon:"🇺🇸",bg:"rgba(26,58,92,.06)",name:"FinCEN",desc:"US Financial Crimes Enforcement Network — collects and analyses financial intelligence to combat crime.",url:"https://www.fincen.gov/",tag:"Intelligence",cls:"s2"}),
    new Organisation({icon:"🕵️",bg:"rgba(192,57,43,.06)",name:"FBI IC3",desc:"Internet Crime Complaint Center — public reporting and analysis of cyber-enabled financial crime.",url:"https://www.ic3.gov/",tag:"Law Enforcement",cls:"s3"}),
    new Organisation({icon:"⚖️",bg:"rgba(26,107,90,.07)",name:"US Department of Justice",desc:"Criminal Division — prosecutes fraud, money laundering, FCPA violations, and financial crime.",url:"https://www.justice.gov/criminal",tag:"Prosecution",cls:"s1"}),
    new Organisation({icon:"🏛️",bg:"rgba(200,144,46,.07)",name:"US Treasury (TFI)",desc:"Office of Terrorism and Financial Intelligence — sanctions, terrorist financing, and financial crime policy.",url:"https://home.treasury.gov/",tag:"Policy",cls:"s4"}),
    new Organisation({icon:"🔍",bg:"rgba(192,57,43,.06)",name:"INTERPOL",desc:"International policing organisation coordinating cross-border financial crime investigations globally.",url:"https://www.interpol.int/en/Crimes/Financial-crime",tag:"Law Enforcement",cls:"s3"}),
    new Organisation({icon:"🏛️",bg:"rgba(26,58,92,.06)",name:"Europol",desc:"EU law enforcement agency tackling money laundering, fraud, and criminal finance across Europe.",url:"https://www.europol.europa.eu/crime-areas/economic-crime",tag:"Law Enforcement",cls:"s2"}),
    new Organisation({icon:"⚖️",bg:"rgba(192,57,43,.06)",name:"UK National Crime Agency",desc:"Lead UK agency combating serious and organised crime including economic crime and cybercrime.",url:"https://www.nationalcrimeagency.gov.uk/",tag:"Law Enforcement",cls:"s3"}),
    new Organisation({icon:"📋",bg:"rgba(26,107,90,.07)",name:"Financial Conduct Authority",desc:"UK regulator ensuring financial markets work well and consumers are protected.",url:"https://www.fca.org.uk/",tag:"Regulator",cls:"s1"}),
    new Organisation({icon:"🏦",bg:"rgba(200,144,46,.07)",name:"Wolfsberg Group",desc:"Association of 13 global banks developing financial crime risk management frameworks.",url:"https://www.wolfsberg-principles.com/",tag:"Industry",cls:"s4"}),
    new Organisation({icon:"🛡️",bg:"rgba(26,107,90,.07)",name:"Slave Free Alliance",desc:"Social enterprise helping organisations protect operations and supply chains from modern slavery.",url:"https://www.slavefreealliance.org/",tag:"Modern Slavery",cls:"s1"}),
    new Organisation({icon:"🔒",bg:"rgba(26,58,92,.06)",name:"Get Safe Online",desc:"UK's leading public/private partnership providing free, impartial online safety advice.",url:"https://www.getsafeonline.org/",tag:"Cyber Safety",cls:"s2"}),
    new Organisation({icon:"🏢",bg:"rgba(192,57,43,.06)",name:"Transparency International",desc:"Global movement working to end the injustice of corruption through advocacy and research.",url:"https://www.transparency.org/",tag:"Anti-Corruption",cls:"s3"}),
    new Organisation({icon:"📊",bg:"rgba(26,107,90,.07)",name:"Egmont Group",desc:"Network of 167 Financial Intelligence Units sharing information to combat ML and TF globally.",url:"https://egmontgroup.org/",tag:"Intelligence",cls:"s1"}),
    new Organisation({icon:"💼",bg:"rgba(200,144,46,.07)",name:"ACAMS",desc:"The largest AML membership organisation globally — certifications, training, and professional community.",url:"https://www.acams.org/",tag:"Professional Body",cls:"s4"}),
    new Organisation({icon:"🎓",bg:"rgba(26,107,90,.07)",name:"International Compliance Association",desc:"Globally recognised qualifications in governance, risk, and compliance.",url:"https://www.int-comp.org/",tag:"Education",cls:"s1"})
];
