class Organisation { constructor({icon,bg,name,desc,url,tag,cls,type}){this.icon=icon;this.bg=bg;this.name=name;this.desc=desc;this.url=url;this.tag=tag;this.cls=cls;this.type=type;} }
const organisations=[
    // ── Standards & Policy ──
    new Organisation({icon:"🌐",bg:"rgba(26,58,92,.06)",name:"FATF",desc:"Financial Action Task Force — the global standard-setter for AML, counter-terrorist financing, and counter-proliferation financing. Issues the 40 Recommendations.",url:"https://www.fatf-gafi.org/",tag:"Standards",cls:"s4",type:"Standards & Policy"}),
    new Organisation({icon:"🏛️",bg:"rgba(200,144,46,.07)",name:"US Treasury (TFI)",desc:"Office of Terrorism and Financial Intelligence — sanctions, terrorist financing, and financial crime policy.",url:"https://home.treasury.gov/",tag:"Policy",cls:"s4",type:"Standards & Policy"}),
    new Organisation({icon:"🇺🇳",bg:"rgba(26,58,92,.06)",name:"UNODC",desc:"UN Office on Drugs and Crime — technical assistance and research on money laundering, corruption, and organised crime worldwide.",url:"https://www.unodc.org/unodc/en/money-laundering/index.html",tag:"International",cls:"s2",type:"Standards & Policy"}),
    // ── Intelligence ──
    new Organisation({icon:"🇺🇸",bg:"rgba(26,58,92,.06)",name:"FinCEN",desc:"US Financial Crimes Enforcement Network — collects and analyses financial intelligence to combat crime.",url:"https://www.fincen.gov/",tag:"Intelligence",cls:"s2",type:"Intelligence"}),
    new Organisation({icon:"📊",bg:"rgba(26,107,90,.07)",name:"Egmont Group",desc:"Network of 167 Financial Intelligence Units sharing information to combat ML and TF globally.",url:"https://egmontgroup.org/",tag:"Intelligence",cls:"s1",type:"Intelligence"}),
    // ── Law Enforcement ──
    new Organisation({icon:"🔍",bg:"rgba(192,57,43,.06)",name:"INTERPOL",desc:"International policing organisation coordinating cross-border financial crime investigations globally.",url:"https://www.interpol.int/en/Crimes/Financial-crime",tag:"Law Enforcement",cls:"s3",type:"Law Enforcement"}),
    new Organisation({icon:"🏛️",bg:"rgba(26,58,92,.06)",name:"Europol",desc:"EU law enforcement agency tackling money laundering, fraud, and criminal finance across Europe.",url:"https://www.europol.europa.eu/crime-areas/economic-crime",tag:"Law Enforcement",cls:"s2",type:"Law Enforcement"}),
    new Organisation({icon:"⚖️",bg:"rgba(192,57,43,.06)",name:"UK National Crime Agency",desc:"Lead UK agency combating serious and organised crime including economic crime and cybercrime.",url:"https://www.nationalcrimeagency.gov.uk/",tag:"Law Enforcement",cls:"s3",type:"Law Enforcement"}),
    new Organisation({icon:"🕵️",bg:"rgba(192,57,43,.06)",name:"FBI IC3",desc:"Internet Crime Complaint Center — public reporting and analysis of cyber-enabled financial crime.",url:"https://www.ic3.gov/",tag:"Law Enforcement",cls:"s3",type:"Law Enforcement"}),
    // ── Prosecution & Regulation ──
    new Organisation({icon:"⚖️",bg:"rgba(26,107,90,.07)",name:"US Department of Justice",desc:"Criminal Division — prosecutes fraud, money laundering, FCPA violations, and financial crime.",url:"https://www.justice.gov/criminal",tag:"Prosecution",cls:"s1",type:"Prosecution & Regulation"}),
    new Organisation({icon:"📋",bg:"rgba(26,107,90,.07)",name:"Financial Conduct Authority",desc:"UK regulator ensuring financial markets work well and consumers are protected from financial crime.",url:"https://www.fca.org.uk/",tag:"Regulator",cls:"s1",type:"Prosecution & Regulation"}),
    // ── Industry & Professional Bodies ──
    new Organisation({icon:"🏦",bg:"rgba(200,144,46,.07)",name:"Wolfsberg Group",desc:"Association of 13 global banks developing financial crime risk management frameworks and guidance.",url:"https://www.wolfsberg-principles.com/",tag:"Industry",cls:"s4",type:"Industry & Professional Bodies"}),
    new Organisation({icon:"💼",bg:"rgba(200,144,46,.07)",name:"ACAMS",desc:"Largest AML membership organisation globally — certifications (CAMS), training, and 100,000+ member professional community.",url:"https://www.acams.org/",tag:"Professional Body",cls:"s4",type:"Industry & Professional Bodies"}),
    new Organisation({icon:"🏢",bg:"rgba(192,57,43,.06)",name:"Transparency International",desc:"Global movement working to end the injustice of corruption through advocacy, research, and the Corruption Perceptions Index.",url:"https://www.transparency.org/",tag:"Anti-Corruption",cls:"s3",type:"Industry & Professional Bodies"}),
    // ── Research & Think Tanks ──
    new Organisation({icon:"🔬",bg:"rgba(26,58,92,.06)",name:"RUSI CFCS",desc:"Royal United Services Institute — Centre for Financial Crime & Security Studies. Leading UK think tank on illicit finance policy and FATF.",url:"https://www.rusi.org/explore-our-research/projects/financial-crime-policy",tag:"Research",cls:"s2",type:"Research & Think Tanks"}),
    new Organisation({icon:"🏔️",bg:"rgba(26,107,90,.07)",name:"Basel Institute on Governance",desc:"Independent not-for-profit working on anti-corruption, asset recovery, and financial crime prevention. Publishes the Basel AML Index.",url:"https://baselgovernance.org/",tag:"Research",cls:"s1",type:"Research & Think Tanks"}),
    // ── Education & Training ──
    new Organisation({icon:"🎓",bg:"rgba(26,107,90,.07)",name:"International Compliance Association",desc:"Globally recognised qualifications in governance, risk, and compliance — 30,000+ members in 155 countries.",url:"https://www.int-comp.org/",tag:"Education",cls:"s1",type:"Education & Training"}),
    new Organisation({icon:"📜",bg:"rgba(200,144,46,.07)",name:"ACFCS",desc:"Association of Certified Financial Crime Specialists — the CFCS credential covering AML, fraud, cyber, sanctions, and corruption.",url:"https://www.acfcs.org/",tag:"Certification",cls:"s4",type:"Education & Training"}),
    new Organisation({icon:"💻",bg:"rgba(26,58,92,.06)",name:"Financial Crime Academy",desc:"Online education platform with 100+ courses and certifications for anti-financial crime and compliance professionals.",url:"https://financialcrimeacademy.org/",tag:"Online Learning",cls:"s2",type:"Education & Training"}),
    new Organisation({icon:"🏫",bg:"rgba(192,57,43,.06)",name:"Middlebury Institute — FCM",desc:"Financial Crime Management graduate certificate — compliance, investigations, and illicit finance analysis.",url:"https://www.middlebury.edu/institute/academics/additional-programs/certificates/financial-crime",tag:"Academic",cls:"s3",type:"Education & Training"}),
    new Organisation({icon:"🏦",bg:"rgba(26,107,90,.07)",name:"ABA Financial Crimes Certificates",desc:"American Bankers Association — BSA/AML compliance and fraud prevention certificate programmes for banking professionals.",url:"https://www.aba.com/training-events/online-training/aml-fraud-professionals-certificates",tag:"Banking Education",cls:"s1",type:"Education & Training"}),
    new Organisation({icon:"🎯",bg:"rgba(200,144,46,.07)",name:"AMLFC Institute",desc:"Professional certification in AML/CFT/financial crime prevention delivered via partner universities with NASBA CPE accreditation.",url:"https://amlfc.institute",tag:"Certification",cls:"s4",type:"Education & Training"}),
    // ── Civil Society & Public Safety ──
    new Organisation({icon:"🛡️",bg:"rgba(26,107,90,.07)",name:"Slave Free Alliance",desc:"Social enterprise helping organisations protect operations and supply chains from modern slavery.",url:"https://www.slavefreealliance.org/",tag:"Modern Slavery",cls:"s1",type:"Civil Society & Public Safety"}),
    new Organisation({icon:"🔒",bg:"rgba(26,58,92,.06)",name:"Get Safe Online",desc:"UK's leading public/private partnership providing free, impartial online safety advice.",url:"https://www.getsafeonline.org/",tag:"Cyber Safety",cls:"s2",type:"Civil Society & Public Safety"})
];
