class FlowStep {
    constructor({ icon, label, sub, title, desc, flags }) {
        this.icon=icon;this.label=label;this.sub=sub;this.title=title;this.desc=desc;this.flags=flags;
    }
}
class FlowStage {
    constructor({ name, color, steps }) { this.name=name;this.color=color;this.steps=steps; }
}
class CrimeFlow {
    constructor({ name, icon, source, stages }) { this.name=name;this.icon=icon;this.source=source;this.stages=stages; }
}
const crimeFlows = [
    new CrimeFlow({ name:"Money Laundering", icon:"💰",
        source:"Patterns based on FinCEN advisories, DOJ case materials & US Treasury (public domain)",
        stages:[
            new FlowStage({ name:"PLACEMENT", color:"192,57,43", steps:[
                new FlowStep({ icon:"💊", label:"Drug Proceeds", sub:"$2M cash from trafficking", title:"Drug Trafficking Proceeds", desc:"A criminal network generates $2 million in cash from drug distribution across multiple states. This bulk cash needs to enter the financial system without triggering Bank Secrecy Act reporting. FinCEN data shows narcotics trafficking remains the largest single source of laundered funds in the US.", flags:["Large volumes of unexplained cash","No legitimate business explanation","Multiple cash collection points"] }),
                new FlowStep({ icon:"🏦", label:"Structuring", sub:"$9,500 × 210 deposits", title:"Structuring Below BSA Thresholds", desc:"The network recruits 15–20 couriers who deposit $9,500 — just below the $10,000 CTR threshold — across dozens of bank branches. Structuring is a federal crime under 31 U.S.C. § 5324 even if the funds are legitimate. FinCEN SARs frequently flag this exact pattern.", flags:["Deposits just below $10,000","Multiple depositors and branches","Sequential or identical amounts"] }),
                new FlowStep({ icon:"🏪", label:"Cash Business", sub:"Car wash, restaurant", title:"Cash-Intensive Business Front", desc:"Some cash is co-mingled with legitimate revenue from a car wash and restaurant. Daily takings are inflated on paper but revenue doesn't match footfall, utilities, or inventory. DOJ and IRS-CI cases frequently feature this method.", flags:["Revenue inconsistent with business type","Unusual cash-to-card ratios","Stock doesn't match reported sales"] })
            ]}),
            new FlowStage({ name:"LAYERING", color:"26,58,92", steps:[
                new FlowStep({ icon:"🏢", label:"Shell Companies", sub:"3 jurisdictions", title:"Shell Company Network", desc:"Funds are transferred to shell companies in Delaware, Cyprus, and the UAE — entities with no employees, offices, or real activity. They generate fictitious invoices for 'consulting.' The Corporate Transparency Act now requires beneficial ownership reporting to FinCEN.", flags:["No genuine business activity","Nominee directors, hidden UBOs","Invoices for vague services"] }),
                new FlowStep({ icon:"🔄", label:"Wire Transfers", sub:"US → Cyprus → Dubai", title:"International Wire Transfers", desc:"Money is wired between shell companies across jurisdictions, each referencing fake invoices. Rapid cross-border movement through multiple correspondent banks makes tracing extremely difficult. FinCEN's 314(b) programme allows banks to share intelligence on suspicious wires.", flags:["Rapid cross-border transfers","Circular payment patterns","Inconsistent with company profile"] }),
                new FlowStep({ icon:"💱", label:"Currency Swap", sub:"USD → EUR → Crypto → GBP", title:"Currency & Crypto Layering", desc:"Funds are converted between currencies at each stage, with some briefly passing through cryptocurrency. The US Treasury has identified virtual asset layering as a growing concern in its National Risk Assessment.", flags:["Multiple conversions without rationale","Brief crypto as layering tool","High-risk jurisdictions"] })
            ]}),
            new FlowStage({ name:"INTEGRATION", color:"26,107,90", steps:[
                new FlowStep({ icon:"🏠", label:"Property", sub:"Luxury real estate", title:"Real Estate Purchases", desc:"The 'clean' money buys luxury apartments in Miami and London. FinCEN's Geographic Targeting Orders (GTOs) require title companies to identify beneficial owners in all-cash real estate deals in major US metros — specifically targeting this typology.", flags:["All-cash or rapid purchases","Properties via LLC structures","Buyer doesn't match property value"] }),
                new FlowStep({ icon:"🚗", label:"Luxury Assets", sub:"Cars, watches, art", title:"High-Value Asset Purchases", desc:"Additional funds buy luxury vehicles, watches, and art — assets that cross borders easily and can be resold for clean cash. These face fewer reporting requirements than real estate transactions.", flags:["Large cash purchases of luxury goods","Third-party purchasers","Assets don't match declared income"] }),
                new FlowStep({ icon:"✅", label:"Clean Income", sub:"Rental, dividends", title:"Legitimate Income Stream", desc:"The criminal now receives rental income and company dividends — all appearing legitimate. The drug trafficking link has been severed across multiple layers of transactions, jurisdictions, and entities.", flags:["Income from laundered-asset investments","Tax returns showing business income","Lifestyle from 'legitimate' sources"] })
            ]})
        ]}),
    new CrimeFlow({ name:"BEC Fraud", icon:"📧",
        source:"Based on FBI IC3 reports and DOJ case materials (public domain)",
        stages:[
            new FlowStage({ name:"TARGETING", color:"200,144,46", steps:[
                new FlowStep({ icon:"🔍", label:"Reconnaissance", sub:"Research target company", title:"Researching the Target", desc:"Criminals spend weeks studying a company's leadership, suppliers, and payment practices using LinkedIn, websites, and breached data. FBI IC3 reports BEC groups increasingly use AI to build convincing profiles and identify the right finance employees to target.", flags:["Scraping corporate social media","Monitoring executive travel","Identifying finance department contacts"] }),
                new FlowStep({ icon:"🎭", label:"Email Compromise", sub:"Spoof CEO account", title:"Email Compromise or Spoofing", desc:"The attacker either compromises a real executive email (through phishing or credential stuffing) or creates a lookalike domain — e.g., c0mpany.com vs company.com. More sophisticated groups use AI to mimic the executive's writing style.", flags:["Lookalike domains registered recently","Login from unusual locations","Auto-forward rules on mailboxes"] }),
                new FlowStep({ icon:"📋", label:"Pretext Crafted", sub:"'Urgent acquisition deal'", title:"Crafting the Pretext", desc:"A convincing scenario is prepared — a confidential acquisition, overdue supplier payment, or regulatory matter — always with urgency and secrecy to bypass verification.", flags:["Scenarios requiring immediate action","Instructions to keep it confidential","References to real business activities"] })
            ]}),
            new FlowStage({ name:"EXECUTION", color:"192,57,43", steps:[
                new FlowStep({ icon:"📧", label:"Fraudulent Email", sub:"'Wire $480K today'", title:"The Fraudulent Instruction", desc:"The spoofed email instructs a finance employee to wire $480,000 to a new account for the 'acquisition.' It references real deals and presses for same-day execution. FBI IC3 data shows average BEC losses of $137,000 per incident, with some exceeding $30 million.", flags:["Payment to new or changed account","Sent outside business hours","Bypass standard approval chains"] }),
                new FlowStep({ icon:"💸", label:"Wire Executed", sub:"$480K to mule account", title:"Funds Transferred", desc:"Believing the instruction is genuine, the finance officer executes the wire. The money lands in a domestic mule account — often a compromised business account or recently opened account controlled by the criminal network.", flags:["Wire to recently opened account","Beneficiary name doesn't match context","Funds moved within hours of receipt"] }),
                new FlowStep({ icon:"🔀", label:"Rapid Movement", sub:"Split and forwarded", title:"Rapid Fund Dispersal", desc:"Within hours, the funds are split across multiple accounts and wired internationally — often to accounts in Southeast Asia or West Africa. Speed is critical: once funds leave the US banking system, recovery drops below 10%.", flags:["Immediate splitting of received funds","International wires within 24 hours","Multiple downstream beneficiaries"] })
            ]}),
            new FlowStage({ name:"EXTRACTION", color:"26,58,92", steps:[
                new FlowStep({ icon:"💱", label:"Crypto Conversion", sub:"BTC via exchanges", title:"Cryptocurrency Conversion", desc:"Portions are quickly converted to cryptocurrency through exchanges with weak KYC — often peer-to-peer platforms or decentralised exchanges. This severs the direct banking trail.", flags:["Quick conversion to crypto","Use of P2P or DEX platforms","Multiple wallet addresses"] }),
                new FlowStep({ icon:"🏧", label:"Cash Withdrawal", sub:"ATMs across countries", title:"Cash Withdrawal Network", desc:"Other portions are withdrawn as cash through ATM networks in multiple countries using prepaid cards loaded from the mule accounts.", flags:["ATM withdrawals in multiple countries","Prepaid cards funded from mule accounts","Withdrawals at maximum daily limits"] }),
                new FlowStep({ icon:"👻", label:"Funds Vanish", sub:"Unrecoverable", title:"Proceeds Disappear", desc:"Within 48–72 hours of the initial wire, the $480,000 has been dispersed across international accounts, converted to crypto, and cashed out — making full recovery virtually impossible.", flags:["Funds in non-cooperative jurisdictions","Mixed crypto and cash channels","No single recovery pathway"] })
            ]})
        ]}),
    new CrimeFlow({ name:"Bribery & Corruption", icon:"💼",
        source:"Based on DOJ FCPA enforcement actions and SEC filings (public domain)",
        stages:[
            new FlowStage({ name:"OPPORTUNITY", color:"26,58,92", steps:[
                new FlowStep({ icon:"🏗️", label:"Govt Contract", sub:"$50M infrastructure bid", title:"The Government Contract", desc:"A multinational company is bidding on a $50 million infrastructure project in a developing country. The procurement process is opaque, and a local official signals that a 'commission' will be needed to secure the award.", flags:["High-value government contract","Opaque procurement process","Intermediary suggests 'facilitation'"] }),
                new FlowStep({ icon:"🤵", label:"Agent Hired", sub:"Local 'consultant'", title:"Engaging the Intermediary", desc:"Rather than paying the official directly, the company hires a local 'consultant' — actually a front for the corrupt official — and signs a consulting agreement with vague deliverables.", flags:["Consultant with no relevant expertise","Vague or non-existent deliverables","Consultant connected to the decision-maker"] }),
                new FlowStep({ icon:"📄", label:"Fake Reports", sub:"Fabricated deliverables", title:"Creating False Justification", desc:"The consultant produces generic 'market research reports' to justify invoicing. In reality, these are templates created solely to generate a paper trail.", flags:["Generic reports with minimal substance","Invoicing before contract award","Deliverables not reviewed by management"] })
            ]}),
            new FlowStage({ name:"CORRUPT PAYMENT", color:"192,57,43", steps:[
                new FlowStep({ icon:"💰", label:"$2.5M Payment", sub:"Via offshore account", title:"The Corrupt Payment", desc:"$2.5 million is wired to the consultant's offshore company in a low-transparency jurisdiction. The consultant passes most of the money to the government official through cash, property purchases, or tuition payments for the official's family.", flags:["Payment to offshore entity","Amount disproportionate to services","Payments coincide with contract milestones"] }),
                new FlowStep({ icon:"🏆", label:"Contract Won", sub:"Company wins $50M bid", title:"Contract Secured", desc:"The company wins the contract — outscoring competitors on evaluation criteria that were adjusted in their favour. The bribe has distorted the procurement process.", flags:["Unexpected contract award","Evaluation criteria changed mid-process","Competing bidders were more qualified"] }),
                new FlowStep({ icon:"🔇", label:"Silenced", sub:"Whistleblowers pressured", title:"Suppressing Internal Concerns", desc:"Junior employees who notice the unusual consultant payments are discouraged from asking questions. Internal audit findings are buried.", flags:["Audit findings not escalated","Staff warned against raising concerns","Compliance function underfunded"] })
            ]}),
            new FlowStage({ name:"CONCEALMENT", color:"26,107,90", steps:[
                new FlowStep({ icon:"📊", label:"Books Falsified", sub:"'Consulting expenses'", title:"Falsifying Books and Records", desc:"The bribe payments are recorded as legitimate consulting expenses in the company's books. The SEC's FCPA books-and-records provision makes this falsification independently criminal.", flags:["Vague expense descriptions","No supporting documentation","Expenses not subject to normal controls"] }),
                new FlowStep({ icon:"🌴", label:"Official Enriched", sub:"Property, school fees", title:"Corrupt Official's Proceeds", desc:"The government official uses the bribe to purchase property, pay children's university fees abroad, and fund a lifestyle far beyond their official salary.", flags:["Lifestyle inconsistent with income","Foreign property purchases","Education or luxury spending spikes"] }),
                new FlowStep({ icon:"🔁", label:"Pattern Repeats", sub:"Embedded in operations", title:"Systemic Corruption", desc:"With one successful bribe, the pattern becomes embedded — the company uses the same consultant and method for future contracts across the region.", flags:["Same intermediary used repeatedly","Pattern across multiple jurisdictions","No management challenge of payments"] })
            ]})
        ]}),
    new CrimeFlow({ name:"Ransomware", icon:"🔐",
        source:"Based on FBI IC3, CISA advisories & FinCEN guidance (public domain)",
        stages:[
            new FlowStage({ name:"ACCESS", color:"192,57,43", steps:[
                new FlowStep({ icon:"🎣", label:"Phishing Email", sub:"Employee clicks link", title:"Initial Access — Phishing", desc:"A hospital employee receives an email appearing to be from a medical supplier with an attached 'invoice.' Clicking the link installs malware. FBI IC3 and CISA report phishing remains the primary initial access vector in over 80% of ransomware attacks on healthcare.", flags:["Email from spoofed trusted sender","Urgent invoice or delivery notice","Link to malicious download"] }),
                new FlowStep({ icon:"🔓", label:"Network Breach", sub:"Lateral movement begins", title:"Network Compromise", desc:"The malware establishes a foothold and the attackers move laterally through the network, escalating privileges and mapping critical systems over weeks or months.", flags:["Unusual account privilege escalation","Lateral movement across segments","Access to backup and admin systems"] }),
                new FlowStep({ icon:"📤", label:"Data Stolen", sub:"Patient records exfiltrated", title:"Data Theft Before Encryption", desc:"Before encrypting anything, the attackers exfiltrate sensitive patient records, financial data, and proprietary information — enabling 'double extortion.'", flags:["Large data transfers to external IPs","Data moved outside business hours","Compression of sensitive archives"] })
            ]}),
            new FlowStage({ name:"EXPLOITATION", color:"26,58,92", steps:[
                new FlowStep({ icon:"🔒", label:"Encrypted", sub:"Hospital operations halted", title:"Ransomware Deployment", desc:"Ransomware is deployed across the hospital's network simultaneously, encrypting electronic health records, scheduling systems, and billing. Critical care reverts to paper.", flags:["Simultaneous encryption across systems","Ransom note displayed on screens","IT unable to access backups"] }),
                new FlowStep({ icon:"💀", label:"$4.5M Demand", sub:"Pay in Bitcoin", title:"The Ransom Demand", desc:"A ransom note demands $4.5 million in Bitcoin within 72 hours, threatening to publish patient records on a dark web leak site.", flags:["Payment demanded in cryptocurrency","Countdown timer creating urgency","Threat to publish stolen data"] }),
                new FlowStep({ icon:"⏱️", label:"Pressure", sub:"Lives at risk", title:"Escalating Pressure", desc:"With systems down, the hospital diverts emergency patients and cancels surgeries. Patient safety is directly at risk. The attackers contact media outlets to increase pressure.", flags:["Patient care directly impacted","Threat actors contact journalists","Regulatory notification deadlines"] })
            ]}),
            new FlowStage({ name:"MONETISATION", color:"200,144,46", steps:[
                new FlowStep({ icon:"₿", label:"BTC Payment", sub:"$4.5M transferred", title:"Ransom Payment", desc:"Under pressure, the hospital's board authorises payment. $4.5 million in Bitcoin is transferred to the attackers' wallet. FinCEN requires ransomware payment processors to file SARs.", flags:["Payment to anonymous crypto wallet","Funds immediately tumbled/mixed","No guarantee of decryption"] }),
                new FlowStep({ icon:"🔀", label:"Crypto Laundered", sub:"Mixers and chain-hopping", title:"Laundering the Ransom", desc:"The Bitcoin is run through mixing services, chain-hopped to Monero and back, and sent through exchanges in jurisdictions with weak AML. US Treasury sanctioned Tornado Cash for this reason.", flags:["Use of sanctioned mixing protocols","Cross-chain swaps to privacy coins","Off-ramping through non-compliant exchanges"] }),
                new FlowStep({ icon:"💵", label:"Cash Out", sub:"Property, luxury goods", title:"Converting to Assets", desc:"The group converts crypto to cash, property, and luxury goods — often in jurisdictions with minimal US extradition cooperation. Only a small fraction of ransomware proceeds are ever recovered.", flags:["Conversion in non-cooperative jurisdictions","Purchase of assets and property","Funds reinvested in criminal infrastructure"] })
            ]})
        ]}),
    new CrimeFlow({ name:"Terrorist Financing", icon:"🕌",
        source:"Based on US Treasury risk assessments and FinCEN advisories (public domain)",
        stages:[
            new FlowStage({ name:"FUNDRAISING", color:"200,144,46", steps:[
                new FlowStep({ icon:"🕊️", label:"Sham Charity", sub:"Humanitarian front", title:"Charity Front Organisation", desc:"A charity is established claiming to provide humanitarian aid to a conflict zone. While some legitimate aid work occurs, a significant portion of donations are diverted. The US Treasury has designated over 70 entities under E.O. 13224 for this.", flags:["Charity operating in conflict zones","Vague programme descriptions","Disproportionate 'admin' costs"] }),
                new FlowStep({ icon:"💻", label:"Online Drives", sub:"Social media campaigns", title:"Digital Fundraising Campaigns", desc:"The organisation runs emotive social media campaigns soliciting small donations from thousands of supporters worldwide. Encrypted messaging groups coordinate donation drives.", flags:["Emotive appeals on social media","Donations via crypto or gift cards","Encrypted group coordination"] }),
                new FlowStep({ icon:"🏪", label:"Business Front", sub:"Import/export company", title:"Business Income Diversion", desc:"A seemingly legitimate import/export business generates real revenue — but a portion is systematically diverted to fund operations. Unlike money laundering, terrorist financing may involve entirely legitimate funds being redirected.", flags:["Legitimate business with unexplained transfers","Profits don't match reinvestment","Trade with high-risk conflict regions"] })
            ]}),
            new FlowStage({ name:"TRANSFER", color:"26,58,92", steps:[
                new FlowStep({ icon:"💱", label:"Hawala", sub:"No formal banking trail", title:"Informal Value Transfer (Hawala)", desc:"Funds are moved internationally through hawala — an informal value transfer system operating on trust between brokers. Money is deposited with a broker in one country and an equivalent released in another with no wire transfer.", flags:["Cash deposits with informal brokers","Corresponding releases in conflict zones","Minimal or no documentation"] }),
                new FlowStep({ icon:"📱", label:"Crypto Transfer", sub:"Bitcoin to conflict zone", title:"Cryptocurrency Transfer", desc:"Some funds are converted to Bitcoin and transferred through a chain of wallets to operatives overseas. Virtual asset service providers in jurisdictions with weak regulation are exploited.", flags:["Crypto to wallets in high-risk regions","Use of unregulated exchanges","Small repeated transfers"] }),
                new FlowStep({ icon:"🧳", label:"Cash Couriers", sub:"Physical transport", title:"Bulk Cash Smuggling", desc:"Physical cash is moved across borders by couriers — sometimes hidden in commercial shipments. US Customs and Border Protection seizes millions in undeclared currency annually.", flags:["Undeclared cross-border cash","Couriers on high-risk routes","Cash hidden in goods shipments"] })
            ]}),
            new FlowStage({ name:"DEPLOYMENT", color:"192,57,43", steps:[
                new FlowStep({ icon:"🔫", label:"Weapons", sub:"Arms on black market", title:"Weapons and Equipment", desc:"In the destination country, funds are used to purchase weapons, communications equipment, vehicles, and supplies through black market networks or corrupt military sources.", flags:["Black market weapons purchases","Untraceable communications equipment","Supplies inconsistent with aid work"] }),
                new FlowStep({ icon:"🏕️", label:"Operations", sub:"Recruitment & logistics", title:"Operational Infrastructure", desc:"Funds support recruitment, training facilities, safe houses, and logistics networks. Apparently small sums can sustain significant operational capacity in low-cost environments.", flags:["Facility rentals in remote areas","Travel bookings for recruits","Subsistence payments to operatives"] }),
                new FlowStep({ icon:"💥", label:"Attack Funded", sub:"Operational execution", title:"Attack Planning & Execution", desc:"Ultimately, the diverted charitable donations, business profits, and transferred funds finance an act of violence. US Treasury analysis shows even modest sums — sometimes under $10,000 — can fund devastating attacks.", flags:["Small amounts funding significant harm","Planning expenses across countries","Complete disconnect from original donors"] })
            ]})
        ]})
];
