/* ═══════════════════════════════════════════
   THE VAULT — Books
   Last updated: March 2026
   ═══════════════════════════════════════════ */
mediaItems.push(
{id:201,title:"Moneyland",type:"book",year:2018,creator:"Oliver Bullough",desc:"How the world\u2019s ultra-rich and corrupt exploit offshore havens, anonymous companies, and complicit professionals to hide their stolen wealth. A tour through the borderless country where the rules don\u2019t apply \u2014 if you can afford the entry fee.",themes:["Money Laundering","Offshore","Kleptocracy"],shelves:["books"],url:"https://www.goodreads.com/book/show/36099412-moneyland",srcLabel:"Goodreads",gradient:"linear-gradient(135deg,#1a0a2e,#16213e,#0f3460)"},
{id:202,title:"Tracers in the Dark",type:"book",year:2022,creator:"Andy Greenberg",desc:"The true story of how a small team of investigators developed blockchain forensics to bring down the world\u2019s biggest darknet markets and crypto launderers. The definitive account of how cryptocurrency lost its anonymity.",themes:["Crypto Crime","Cyber Crime","Investigation"],shelves:["hero","books"],featured:true,featuredTagline:"The blockchain never forgets. Neither do they.",url:"https://www.goodreads.com/book/show/60462182-tracers-in-the-dark",srcLabel:"Goodreads",gradient:"linear-gradient(135deg,#0d1117,#161b22,#21262d)"},
{id:203,title:"Kleptopia",type:"book",year:2020,creator:"Tom Burgis",desc:"How dirty money is conquering the world. Traces the flows of corrupt cash from Central Asia through the City of London and into Western democracies. A masterwork of investigative journalism that reads like a thriller.",themes:["Kleptocracy","Money Laundering","Offshore"],shelves:["books"],url:"https://www.goodreads.com/book/show/49114729-kleptopia",srcLabel:"Goodreads",gradient:"linear-gradient(135deg,#0a0a1a,#1a0a2e,#2d0a3e)"},
{id:204,title:"Billion Dollar Whale",type:"book",year:2018,creator:"Tom Wright & Bradley Hope",desc:"The incredible true story of 1MDB \u2014 how one young man stole billions from Malaysia\u2019s sovereign wealth fund and lived the most extravagant life imaginable. Yachts, Hollywood, and a trail of devastation.",themes:["Fraud","Money Laundering","Kleptocracy"],shelves:["books"],url:"https://www.goodreads.com/book/show/38743564-billion-dollar-whale",srcLabel:"Goodreads",gradient:"linear-gradient(135deg,#1a1a0a,#2d2d0a,#3d3d0a)"},
{id:205,title:"Butler to the World",type:"book",year:2022,creator:"Oliver Bullough",desc:"How Britain became the servant of corrupt wealth \u2014 from kleptocrats parking dirty money in London property to the army of lawyers, accountants, and fixers who make it all possible.",themes:["Money Laundering","Offshore","Kleptocracy","Regulation"],shelves:["books"],url:"https://www.goodreads.com/book/show/58950859-butler-to-the-world",srcLabel:"Goodreads",gradient:"linear-gradient(135deg,#0d1117,#1a0a0a,#2d1515)"},
{id:206,title:"The Spider Network",type:"book",year:2017,creator:"David Enrich",desc:"The true story of Tom Hayes and the LIBOR rigging scandal \u2014 how a small group of traders manipulated the world\u2019s most important interest rate, affecting trillions in financial contracts worldwide.",themes:["Wall Street","Banking","Corporate Fraud"],shelves:["books"],url:"https://www.goodreads.com/book/show/30755418-the-spider-network",srcLabel:"Goodreads",gradient:"linear-gradient(135deg,#1a1a2e,#0a0a1a,#16213e)"}
);
