/* ═══════════════════════════════════════════
   THE VAULT — Films & Television
   Last updated: March 2026
   ═══════════════════════════════════════════ */
mediaItems.push(
{id:101,title:"The Big Short",type:"film",year:2015,creator:"Dir. Adam McKay",desc:"The true story of the traders who predicted and profited from the 2008 financial crisis, exposing systemic fraud in mortgage-backed securities. A visceral, fourth-wall-breaking masterpiece that makes CDOs and credit default swaps terrifyingly entertaining.",themes:["Wall Street","Corporate Fraud","Banking"],shelves:["hero","films"],featured:true,featuredTagline:"The film that taught a generation how the banks really work.",url:"https://www.imdb.com/title/tt1596363/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)"},
{id:102,title:"The Wolf of Wall Street",type:"film",year:2013,creator:"Dir. Martin Scorsese",desc:"Jordan Belfort\u2019s rise and fall through securities fraud, money laundering, and corruption on Wall Street. A masterclass in how pump-and-dump schemes work \u2014 excess, greed, and zero remorse.",themes:["Wall Street","Money Laundering","Fraud"],shelves:["hero","films"],featured:true,featuredTagline:"Greed is good. Until the FBI shows up.",url:"https://www.imdb.com/title/tt0993846/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#0d0d0d,#1a0a0a,#2d1010)"},
{id:103,title:"The Laundromat",type:"film",year:2019,creator:"Dir. Steven Soderbergh",desc:"Based on the Panama Papers scandal, exploring how shell companies and offshore structures enable the global elite to hide wealth and evade taxes. Meryl Streep leads this dark comedy about the machinery of financial secrecy.",themes:["Money Laundering","Offshore","Corporate Fraud"],shelves:["films"],url:"https://www.imdb.com/title/tt5865326/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#0a192f,#112240,#1d3557)"},
{id:104,title:"Ozark",type:"tv",year:2017,creator:"Netflix \u00b7 2017\u20132022",desc:"A financial planner launders money for a Mexican drug cartel in Missouri\u2019s Lake of the Ozarks. One of the most detailed fictional portrayals of placement, layering, and integration in TV history. Four seasons of escalating moral bankruptcy.",themes:["Money Laundering","Organised Crime"],shelves:["hero","films"],featured:true,featuredTagline:"Every dollar has a story. Most of them are lies.",url:"https://www.imdb.com/title/tt5071412/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#0b1622,#162447,#1f4068)"},
{id:105,title:"McMafia",type:"tv",year:2018,creator:"BBC/AMC \u00b7 2018",desc:"A Russian-British banker is drawn into the world of organised crime. Highlights trade-based money laundering, hawala networks, and the role of professional enablers who make global dirty money flows possible.",themes:["Money Laundering","Organised Crime","Sanctions"],shelves:["films"],url:"https://www.imdb.com/title/tt6271080/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#1a0000,#2d0a0a,#0d1117)"},
{id:106,title:"Bad Blood: The Final Chapter",type:"tv",year:2022,creator:"TV Series \u00b7 2022",desc:"Based on the true story of the Rizzuto crime family in Montreal, showing how organised crime infiltrates legitimate business through money laundering and intimidation.",themes:["Organised Crime","Money Laundering"],shelves:["films"],url:"https://www.imdb.com/title/tt6423776/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#0d0d0d,#1a1a1a,#2d1515)"},
{id:107,title:"Dirty Money",type:"documentary",year:2018,creator:"Netflix \u00b7 2018\u20132020",desc:"Documentary series exploring corporate fraud, corruption, and financial crime. Each episode covers a different scandal \u2014 from VW emissions fraud to payday lending empires to maple syrup cartels. Essential viewing for compliance professionals.",themes:["Corporate Fraud","Regulation","Banking"],shelves:["films"],url:"https://www.imdb.com/title/tt7889220/",srcLabel:"IMDb",gradient:"linear-gradient(135deg,#0a0a0a,#1a1a0a,#2d2d0a)"}
);
